apiVersion: apps/v1
kind: Deployment
metadata:
  name: task3b-deployment
  labels:
    app: task3b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task3b
  template:
    metadata:
      labels:
        app: task3b
    spec:
      containers:
        - name: task3b-cont
          image: kondavenkat035/train:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: task3b-node-service
spec:
  selector:
    app: task3b
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
